### ISSUE TITLE
Оценка проекта

### ISSUE THREAD

**Issue by dakand** [atls/orbitto#1]
@TorinAsakura @TFK70 Я решил создать сервис помогающий арбитражникам криптовалют находить наиболее выгодные связки. Потенциал для расширения достаточно большой, но пока мы ограничемся P2P Binance.
1. Разработал [интерфейс](https://www.figma.com/file/fpoeezViAZJSXXhizspqof/Orbitto?node-id=149%3A22687). на данный момент работаю над админкой.
2. Создал [окружение в notion](https://classy-mass-d16.notion.site/Orbitto-9d3ff57cdfd14bdfa9e2b5d3327a60d7), в котором будут описаны все бизнес-процессы, планирование и прочее. На данный момент там информация для понимания проекта для вас, как для разработчиков.
Нужно оценить проект. Сколько примерно чистого и грязного времени на него уйдёт. Также стоит выписать те пункты в разработки, которые будут самыми ресурсозатратными.

В идеале бы хотелось запуститься недели через 3, но желательно не позже 1 сентября. К этому времени я подготовлю сайт, создам все соц. сети и отсниму контент для соц. сетей.

Сама тема набирает обороты ежедневно, всё новые конкуренты с гугл таблицами появляются на горизонте. Это ещё одна причина почему хочется запустить продукт как можно быстрее.

---

P.S. @TorinAsakura сорян, в ноушене много всего получилось с таблицами и линками. Не могу в гх перенести всё это. Для оценки проекта надеюсь вы воспользуетесь ноушеном, а уже по результату какие-то технически фундаментальные вещи буду вытаскивать в гх.

**Comment by TFK70** [comment]
Трекается [тут](https://github.com/atls/orbitto/milestone/1)

**Comment by dakand** [comment]
@TFK70 @TorinAsakura уже есть примерная оценка по времени разработки?

**Comment by TorinAsakura** [comment]
@dakand По идее до первого сентября должно успеться
