### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by TFK70** [atls/orbitto#12]
### Список задач

- [x] https://github.com/atls/orbitto/issues/5
- [x] https://github.com/atls/orbitto/issues/6
- [x] https://github.com/atls/orbitto/issues/7
- [x] https://github.com/atls/orbitto/issues/8
- [x] https://github.com/atls/orbitto/issues/9
- [x] https://github.com/atls/orbitto/issues/10
- [ ] https://github.com/atls/orbitto/issues/17
- [ ] https://github.com/atls/orbitto/issues/18

**Comment by brusselboy** [comment]
## Не билдится дэшбоард
@TFK70 

### Описание
Если сбилдить приложение, падает ошибка. Связана она из-за некста, а именно как я понял из-за `next.config.js`

### Шаги воспроизведения

1. `yarn workspace @dashboard/renderer-entrypoint build`
2. Видим ошибку

### Логи
Версия некста последняя - 12.2.5
<details>

```
> Build error occurred
Error: Call retries were exceeded
    at ExperimentalWorker.initialize (/orbitto/.yarn/__virtual__/next-virtual-b7cdc9f97c/0/cache/next-npm-12.2.5-8247fb1613-e8fcbd93d7.zip/node_modules/next/dist/compiled/jest-worker/index.js:1:16346)
    at ExperimentalWorker._onExit (/orbitto/.yarn/__virtual__/next-virtual-b7cdc9f97c/0/cache/next-npm-12.2.5-8247fb1613-e8fcbd93d7.zip/node_modules/next/dist/compiled/jest-worker/index.js:1:17280)
    at Worker.emit (node:events:527:28)
    at Worker.[kOnExit] (node:internal/worker:278:10)
    at Worker.<computed>.onexit (node:internal/worker:198:20) {
  type: 'WorkerError'
}

```

</details>

### Дополнение
Пробовал даунгрейдить некст - эта ошибка уходит, но при билде появляются другие, например:

`next: 12.1.0` - просит установить типы для реакта, когда они уже [установлены](https://github.com/atls/orbitto/blob/feat/init-frontend/package.json#L26):
<details>

```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

        npm install --save-dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).

info  - Checking validity of types .%  
```

</details>

`next: 12.1.6` - не может найти express, когда он также [установлен](https://github.com/atls/orbitto/blob/feat/init-frontend/dashboard/entrypoints/renderer/package.json#L18):

<details>

```
Failed to compile.

./index.ts:1:21
Type error: Cannot find module 'express' or its corresponding type declarations.

> 1 | import express from 'express'
    |                     ^
  2 | import next    from 'next'
  3 | import path    from 'path'
  4 | 

```

</details>

### Вопрос
Нужна помощь, облазил весь инет по каждой ошибке на разных версиях некста, ничего не помогло

**Comment by TFK70** [comment]
@brusselboy 

`typescript@4.4.4`

`next@12.1.0`

`@types/react@18.0.1`
