### ISSUE TITLE
Settings flow

### ISSUE THREAD

**Issue by TFK70** [atls/orbitto#17]
### Задача

Реализовать [флоу изменения пароля](https://www.figma.com/file/fpoeezViAZJSXXhizspqof/Orbitto-%7C-Service?node-id=84%3A9898)

**Comment by monstrs** [comment]
![Screenshot 2022-09-07 at 12 14 46](https://user-images.githubusercontent.com/3871403/188853349-d8d5cf3b-07c0-4bdc-81e8-31cb80d6ef73.png)

@TorinAsakura тк мы работаем с кратосом, текущая реализация дизайна нереализуема, у нас отдельный identity

**Comment by TorinAsakura** [comment]
@monstrs нам просто это перерисовать и вынести в отдельные страницы? Это просто рисунок, нам абсолютно не важно на каких урлах это будет реализовано, главное это два поля - email и password

**Comment by monstrs** [comment]
> @monstrs нам просто это перерисовать и вынести в отдельные страницы? Это просто рисунок, нам абсолютно не важно на каких урлах это будет реализовано, главное это два поля - email и password

вообще не понял о чем ты, у нас kratos и отдельная страница с настройками, в текущей конфигурации это - email и пароль (на картинке выше), смысл в том что эту задачку брать в работу нельзя, тк не соответствует действительности, соответственно у нас два выхода - оставить то что есть на proto ui или нарисовать новую, что не относится к этой задачке

**Comment by TorinAsakura** [comment]
> > @monstrs нам просто это перерисовать и вынести в отдельные страницы? Это просто рисунок, нам абсолютно не важно на каких урлах это будет реализовано, главное это два поля - email и password
> 
> вообще не понял о чем ты, у нас kratos и отдельная страница с настройками, в текущей конфигурации это - email и пароль (на картинке выше), смысл в том что эту задачку брать в работу нельзя, тк не соответствует действительности, соответственно у нас два выхода - оставить то что есть на proto ui или нарисовать новую, что не относится к этой задачке

перерисуем флоу по кратосу, обновим таску, суть у таски не изменится

**Comment by monstrs** [comment]
> > > @monstrs нам просто это перерисовать и вынести в отдельные страницы? Это просто рисунок, нам абсолютно не важно на каких урлах это будет реализовано, главное это два поля - email и password
> > 
> > 
> > вообще не понял о чем ты, у нас kratos и отдельная страница с настройками, в текущей конфигурации это - email и пароль (на картинке выше), смысл в том что эту задачку брать в работу нельзя, тк не соответствует действительности, соответственно у нас два выхода - оставить то что есть на proto ui или нарисовать новую, что не относится к этой задачке
> 
> перерисуем флоу по кратосу, обновим таску, суть у таски не изменится

ок, если что, при передаче задачек на фронт, я деприкейтнул парочку моментов:
* оставил только один тип инпутов, как в форме редактирования пароля, сейчас их несколько разных видов, не вижу смысла устраивать кашу в таком маленьком проекте
* оставил один вид layouta для всех Identity flow, сейчас регистрация/логин имеет один лайаут, а востановление пароля другой
