### ISSUE TITLE
Сервис ligaments

### ISSUE THREAD

**Issue by TFK70** [atls/orbitto#2]
## Задача

Сделать ligaments сервис, находящий [связки](https://classy-mass-d16.notion.site/b29d8113ee6f4585aee7c524ce50d915)

## Детали

Так как [ccxt](https://github.com/ccxt/ccxt) не предоставляет binance p2p api использовать его нам нет смысла. Для получения нужных нам предложений нужно обращаться на эндпоинт `https://p2p.binance.com/bapi/c2c/v2/friendly/c2c/adv/search` (запрос на этот же эндпоинт можно увидеть в нетворке в инспекторе)

Пример запроса:

```typescript
import fetch from 'node-fetch'

const bootstrap = async () => {
  const res = await fetch('https://p2p.binance.com/bapi/c2c/v2/friendly/c2c/adv/search', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{"page":1,"rows":10,"payTypes":[],"countries":[],"asset":"BTC","fiat":"USD","publisherType":"merchant","tradeType":"BUY"}' })
  const d = await res.json()

  console.log(d)
}

bootstrap()
```

Ответ:

```shell
orbitto-sequences-1  | ➤ YN0000: │ webpack {
orbitto-sequences-1  | ➤ YN0000: │ webpack   code: '000000',
orbitto-sequences-1  | ➤ YN0000: │ webpack   message: null,
orbitto-sequences-1  | ➤ YN0000: │ webpack   messageDetail: null,
orbitto-sequences-1  | ➤ YN0000: │ webpack   data: [
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] },
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] },
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] },
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] },
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] },
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] },
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] },
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] },
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] },
orbitto-sequences-1  | ➤ YN0000: │ webpack     { adv: [Object], advertiser: [Object] }
orbitto-sequences-1  | ➤ YN0000: │ webpack   ],
orbitto-sequences-1  | ➤ YN0000: │ webpack   total: 63,
orbitto-sequences-1  | ➤ YN0000: │ webpack   success: true
orbitto-sequences-1  | ➤ YN0000: │ webpack }
```

Таким образом мы можем получать нужные нам офферы **с пейджером** и **без авторизации**

### Общее описание

Так как на будущее подразумевается несколько видов арбитража (между биржами, DEX) - на каждый вид у нас будет отдельная ручка. Сейчас мы рассматриваем только арбитраж внутри биржи, так что:

**Ручка** - `getInsideMarketLigaments `

Для того чтобы получить список связок нужны следующие данные:

- Тип взаимодействия (maker-taker, taker-maker и тд)
- Сумма (`optional`)
- Спред (`optional`)
- Способ пополнения (`optional`)
- Токен (`optional`)
- sortBy ([варианты](https://www.figma.com/file/fpoeezViAZJSXXhizspqof/Orbitto?node-id=50%3A5227))

### Protos

**ligaments.types.proto:**

<details>

```protobuf
syntax = "proto3";

package team.orbitto.ligaments.v1alpha1;

enum InteractionType {
  MAKER_MAKER = 0;
  MAKER_TAKER = 1;
  TAKER_MAKER = 2;
  TAKER_TAKER = 3;
}

message SpreadRange {
  float from = 1;
  float to = 2;
}

enum Liquidity {
  GOOD = 0;
  AVERAGE = 1;
  LOW = 2;
}

enum PaymentMethod {
  TINKOFF = 0;
  ROSBANK = 1;
  RAIFFAISENBANK = 2;
  QIWI = 3;
  YOOMONEY = 4;
  A_BANK = 5;
}

enum Coin {
  USDT = 0;
  BTC = 1;
  BUSD = 2;
  BNB = 3;
  ETH = 4;
  RUB = 5;
  SHIB = 6;
}

enum SortBy {
  IN_ORDER = 0;
  BEST_SPREADS = 1;
  WORST_SPREADS = 2;
}

message WithdrawalOperation {
  Coin coin = 1;
  PaymentMethod paymentMethod = 2;
}

message LigamentNode {
  Coin coin = 1;
}

message Ligament {
  string spread = 1;
  Liquidity liquidity = 2;
  WithdrawalOperation in = 3;
  WithdrawalOperation out = 4;
  repeated LigamentNode nodes = 5;
}

```

</details>

**ligaments.payloads.proto:**

<details>

```protobuf
syntax = "proto3";

package team.orbitto.ligaments.v1alpha1;

import "team/orbitto/ligaments/v1alpha1/ligaments.types.proto";

message GetInsideMarketLigamentsRequest {
  InteractionType interactionType = 1;
  string limits = 2;
  SpreadRange spread = 3;
  repeated Liquidity liquidity = 4;
  repeated PaymentMethod paymentMethod = 5;
  repeated Coin coin = 6;
  SortBy sortBy = 7;
}

message GetInsideMarketLigamentsResponse {
  repeated Ligament ligaments = 1;
}

```

</details>

**ligaments.service.proto:**

<details>

```protobuf
syntax = "proto3";

package team.orbitto.ligaments.v1alpha1;

import "team/orbitto/ligaments/v1alpha1/ligaments.payloads.proto";

service LigamentsService {
  rpc getInsideMarketLigaments(GetInsideMarketLigamentsRequest) returns (GetInsideMarketLigamentsResponse) {}
}

```

</details>

## Алгоритм работы

![flow](https://user-images.githubusercontent.com/62806448/183917437-9aae9d4c-f673-4b9e-a332-238b47846cae.png)

### Алгоритм поиска связок

По сути это просто переписанный алгоритм [отсюда](https://classy-mass-d16.notion.site/b29d8113ee6f4585aee7c524ce50d915), это просто сделано для большей ясности

_Рассматриваем на примере Maker-Taker_

Начинаем поиск связок со следующего:

**Токен покупки** USDT Tinkoff

1. Так как покупаем как мейкер - получаем список предложений на покупку **USDT Тинькофф** (токен покупки)
2. Продаем как тейкер, значит нам тоже нужен список предложений на покупку **USDT**, варьируя способы оплаты. То есть **USDT Тинькофф**, **USDT А-Банк** и тд, пока не переберем все способы оплаты
3. Меняем токен продажи с **USDT** на следующий (например, **BTC**) и повторяем для него тот же алгоритм: **BTC Тинькофф**, **BTC А-Банк** и тд
4. Когда таким образом переберем все токены и способы оплаты для токена продажи - меняем токен покупки по тому же алгоритму. Теперь мы покупаем **USDT А-Банк** и подбираем для него связки по алгоритму выше
5. Когда переберем все способы оплаты для токена покупки - меняем сам токен (на тот же **BTC, например**) и так далее по кругу

**Comment by TFK70** [comment]
@TorinAsakura @dakand Добавил в задачу инфы только что, готов имплементить сервис, проверьте пожалуйста на случай если я что-то упустил или не так понял или дайте аппрув

**Comment by dakand** [comment]
> @TorinAsakura @dakand Добавил в задачу инфы только что, готов имплементить сервис, проверьте пожалуйста на случай если я что-то упустил или не так понял или дайте аппрув

@TFK70 упустил спотовые курсы пар. Т.е. у нас должен быть путь связывающий токен покупки и токен продажи, поэтому сначала парсим цены данных [спотовых пар](https://www.notion.so/13d2a3ce59d246f3940f52a27ef9ca07#5ade52b2931147b7bed0b9e0cbc7d380) и при просчёте одной связки выполняем алгоритм:

> если токен 1 = токен 2, то
> спред = цена токена 2 / цена токена 1
> иначе ищем в списке спотовую пару с участием токена 1 и токена 2
> > если находим, то
> спред = цена токена 2 * спотовый курс / цена токена 1
> иначе методом перебора ищем связку из двух спотовых переводов
> >>если находим, то
> спред = цена токена 2 * спотовый курс1 * спотовый курс 2 / цена токена 1

**На примере связка:**
USDT Росбанк = 60.00 Р ; BNB ЮMoney = 19000.00 Р; Курс USDT/BNB = 0.0033
1. Токен 1 (USDT) ≠ Токен 2 (BNB), поэтому первое условие не выполняется.
2. Перебираем список и находим курс USDT/BNB.
3. Считаем спред, как 19000*0.0033 / 60 = **1.045**

**На примере связка:**
ETH Росбанк = 100000.00 Р ; SHIB ЮMoney = 0.0008 Р; Курс ETH/USDT = 1600; Курс USDT/SHIB = 83400
1. Токен 1 (ETH) ≠ Токен 2 (SHIB), поэтому первое условие не выполняется.
2. Перебираем список и не находим курс.
3. Начинаем перебирать несколько переводов и находим два пути: 
-- ETH/USDT → USDT/SHIB
-- ETH/BUSD → BUSD/SHIB
4. Выбираем один из вариантов* (выбрали ETH/USDT → USDT/SHIB)
5. Считаем спред, как 0.0008*1600*83400 / 100000 = **1,067**

---

*Тут стоит найти все пути и выбирать самое большое произведение курсов. Если нужно, могу написать все связки для которых нужно 2 перевода.

**Comment by TFK70** [comment]
### Состояние

В domain слое описан каркас алгоритма поиска связок:

1. Реализован [цикл](https://github.com/atls/orbitto/blob/feat/init-backend/ligaments/core/domain-module/src/services/ligaments-calculator.service.ts#L98) перебора связок со всеми условиями
2. Реализован подсчет ликвидности связки
3. **НЕ** реализован перебор токена/способа оплаты у токена покупки/продажи (должен быть [тут](https://github.com/atls/orbitto/blob/feat/init-backend/ligaments/core/domain-module/src/services/ligaments-calculator.service.ts#L95)). Сейчас в учет берется только тип взаимодействия (MAKER-TAKER, MAKER-MAKER и тд)

Спотовые курсы валют планируется брать [отсюда](https://binance-docs.github.io/apidocs/spot/en/#symbol-price-ticker) (`curl https://api.binance.com/api/v3/ticker/price\?symbol\=LTCBTC`)
