### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by TFK70** [atls/orbitto#3]
### Список задач

- [x] https://github.com/torin-asakura/orbitto/issues/2
- [ ] https://github.com/torin-asakura/orbitto/issues/21
- [ ] https://github.com/torin-asakura/orbitto/issues/22
- [ ] https://github.com/torin-asakura/orbitto/issues/23
- [ ] https://github.com/torin-asakura/orbitto/issues/24

**Comment by TFK70** [comment]
### Предварительный план работ

- 25 авг. - 30% времени на #2, переделать работу со спот рейтами, закончить алгоритм
- 26 авг. - 30% времени на #2, подготовить gateway, dto, интеграционные тесты
- 30 авг. - 30% времени на #2/#21, скорее всего что-то из #2 сделать не успею, добью в этот день. Также начну инитить протосы для #21
- 31 авг. - 30% времени на #21, финализация сервиса подписок
- 1 сент. - 30% времени на #24, полностью готовый сервис по работе с ролями
- 2 сент. - 30% времени на #22, подготовка сервиса для работы, kratos controller, поля для хранения данных о подписке в юзере
- 5 сент. - 30% времени на #22, реализация логики обновления подписок, их актуализации по крону
- 6 сент. - 30% времени на #23, инициализация протосов, актуализация [либы](https://github.com/atls/tinkoff) до нашего стека
- 7 сент. - 30% времени на #23, финализация сервиса/тестирование сервиса
- 8 сент. - 30% времени на #23, финализация сервиса/тестирование сервиса (полагаю, что-то в теории может пойти не так)

**Comment by dakand** [comment]
@TFK70 тут актуальный прогресс?

**Comment by TFK70** [comment]
> @TFK70 тут актуальный прогресс?

Да, я еще на стадии сервиса ligaments, я просто не детализирую с какими именно проблемами сталкиваюсь

Но сервис уже готов на 90%+, в ближайшее время начну разработку остальных сервисов, там все быстрее должно быть
