### ISSUE TITLE
Вопросы по сущностям

### ISSUE THREAD

**Issue by monstrs** [atls/orbitto#40]
@TFK70 можешь подсказать по сущностям Ligaments?
Что такое `LigamentNode`, для чего нужна и где предполагалась выводиться в интерфейсе?

**Comment by TFK70** [comment]
`LigamentNode` принадлежит `Ligament` и отображает шаг преобразования первоначального токена

В процессе подсчета связки в туда [кладётся](https://github.com/atls/orbitto/blob/master/ligaments/core/domain-module/src/services/ligaments-calculator.service.ts#L147) `coin`, через который мы проходим

В интерфейсе выводится тут:

![Снимок экрана 2022-09-29 в 14 57 15](https://user-images.githubusercontent.com/62806448/193003126-6011a3b2-22f1-46cf-81c6-2a7e24d93845.png)

**Comment by TFK70** [comment]
В самой сущности `Ligaments` они хранятся в массиве, так как в связке может быть больше одного перехода из токена в токен

Это [третий](https://github.com/atls/orbitto/blob/master/ligaments/core/domain-module/src/services/ligaments-calculator.service.ts#L232) случай который отрабатывается при подсчёте связки, если связки `buyTokenOrder.coin -> sellTokenOrder.coin` не существует в массиве [SPOT_PAIRS](https://github.com/atls/orbitto/blob/master/ligaments/core/domain-module/src/constants/spot-pairs.constant.ts), и подсчитывается [промежуточный coin](https://github.com/atls/orbitto/blob/master/ligaments/core/domain-module/src/services/ligaments-calculator.service.ts#L203), и наша связка будет выглядеть как `buyTokenOrder.coin -> intermediateCoin -> sellTokenOrder.coin`
